export {
  adjustEnemyStatusDuration,
  advancePlayerChain,
  applyLifesteal,
  calculateBaseResolvedDamageValue,
  calculatePotentialDamageValue,
  calculateResolvedDamageValue,
  createDamageRuntime,
  finalizeResolvedDamageValue,
  getDocFromDeps,
  getWinFromDeps,
  handleEnemyDamagePrevention,
  resolveEnemyDamageResult,
  resolveEnemyStatusTargetIndex,
  resolveIncomingPlayerDamage,
  resolveShieldGainAmount,
  resolveEnemyTargetIndex,
  runDealDamageClassHook,
} from '../application/damage_system_runtime_helpers.js';
