/**
 * @deprecated compat-only barrel. Prefer narrow support ports from this directory.
 */
export {
  bindTooltipTrigger,
  createRewardReturnActions,
  createTooltipTriggerEvent,
  getEnemyAnchor,
  getStoryOverlayElement,
  getViewportSummary,
  isActivePanel,
  isInlineBlockVisible,
  isTitleSurfaceActive,
  isVisibleElement,
  pickDefinedRefs,
  playAttackCritical,
  playAttackHeavy,
  playAttackSlash,
  playClassSelect,
  playEventBossPhase,
  playEventResonanceBurst,
  playReactionEnemyDeath,
  playReactionPlayerHit,
  playReactionPlayerDeath,
  playStatusEcho,
  playStatusHeal,
  playStatusSkill,
  playUiCard,
  playUiClick,
  playUiFootstep,
  playUiItemGet,
  playUiItemGetFeedback,
  playUiLegendary,
  readTextContent,
  resolveNodePosition,
  resolveNodeTotal,
  toFiniteNumber,
} from '../../../shared/public_feature_support.js';
