export const GS = {
    currentScreen: 'title',
    meta: {
        runCount: 1, totalKills: 0, bestChain: 0, echoFragments: 0,
        worldMemory: {},
        inscriptions: { echo_boost: false, resilience: false, fortune: false },
        storyPieces: [], _hiddenEndingHinted: false,
        codex: { enemies: new Set(), cards: new Set(), items: new Set() },
        unlocks: { ascension: false, endless: false },
        maxAscension: 0,
        runConfig: { ascension: 0, endless: false, blessing: 'none', curse: 'none' },
        progress: { echoShards: 0, totalDamage: 0, victories: 0, failures: 0, bossKills: {} },
    },
    player: {
        class: 'swordsman', hp: 80, maxHp: 80, shield: 0,
        echo: 0, maxEcho: 100, echoChain: 0,
        energy: 3, maxEnergy: 3, gold: 0, kills: 0,
        deck: [], hand: [], graveyard: [], exhausted: [],
        items: [], buffs: {}, silenceGauge: 0, zeroCost: false, _freeCardUses: 0, costDiscount: 0, _cascadeCards: new Map(),
        upgradedCards: new Set(), _cardUpgradeBonus: {},
    },
    currentRegion: 0, currentFloor: 1,
    mapNodes: [], currentNode: null, visitedNodes: new Set(),
    combat: { active: false, enemies: [], turn: 0, playerTurn: true, log: [] },
    _selectedTarget: null,
    worldMemory: {},
    runConfig: { ascension: 0, endless: false, endlessMode: false, blessing: 'none', curse: 'none' },
    stats: { damageDealt: 0, damageTaken: 0, cardsPlayed: 0, maxChain: 0 },
    _heartUsed: false, _temporalTurn: 0, _bossAdvancePending: false,
};
