export const INPUT_ACTION_IDS = Object.freeze({
  CONFIRM: 'confirm',
  CANCEL: 'cancel',
  PAUSE: 'pause',
  HELP: 'help',
  DECK_VIEW: 'deckView',
  CODEX: 'codex',
  END_TURN: 'endTurn',
  ECHO_SKILL: 'echoSkill',
  DRAW_CARD: 'drawCard',
  TARGET_CYCLE: 'targetCycle',
});

export const INPUT_ACTION_CONFIRM = INPUT_ACTION_IDS.CONFIRM;
export const INPUT_ACTION_CANCEL = INPUT_ACTION_IDS.CANCEL;
export const INPUT_ACTION_PAUSE = INPUT_ACTION_IDS.PAUSE;
export const INPUT_ACTION_HELP = INPUT_ACTION_IDS.HELP;
export const INPUT_ACTION_DECK_VIEW = INPUT_ACTION_IDS.DECK_VIEW;
export const INPUT_ACTION_CODEX = INPUT_ACTION_IDS.CODEX;
export const INPUT_ACTION_END_TURN = INPUT_ACTION_IDS.END_TURN;
export const INPUT_ACTION_ECHO_SKILL = INPUT_ACTION_IDS.ECHO_SKILL;
export const INPUT_ACTION_DRAW_CARD = INPUT_ACTION_IDS.DRAW_CARD;
export const INPUT_ACTION_TARGET_CYCLE = INPUT_ACTION_IDS.TARGET_CYCLE;

export const INPUT_ACTION_VALUES = Object.freeze(Object.values(INPUT_ACTION_IDS));
