export const ACHIEVEMENTS = Object.freeze({
  first_victory: {
    id: 'first_victory',
    title: '첫 승리',
    description: '처음으로 런을 승리로 마무리했다.',
    icon: '🏁',
    trigger: 'run_completed',
    category: 'run',
    scope: 'account',
    condition: { type: 'victories', count: 1 },
    rewards: [{ type: 'unlock', contentType: 'curse', contentId: 'blood_moon' }],
  },
  cursed_conqueror_1: {
    id: 'cursed_conqueror_1',
    title: '저주 정복자 I',
    description: '저주를 건 상태로 첫 승리를 달성했다.',
    icon: '🩸',
    trigger: 'run_completed',
    category: 'challenge',
    scope: 'account',
    condition: { type: 'cursed_victories', count: 1 },
    rewards: [{ type: 'unlock', contentType: 'curse', contentId: 'void_oath' }],
  },
  veteran_victory_3: {
    id: 'veteran_victory_3',
    title: '베테랑의 발걸음',
    description: '누적 3회 승리를 달성했다.',
    icon: '🎖',
    trigger: 'run_completed',
    category: 'run',
    scope: 'account',
    condition: { type: 'victories', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'curse', contentId: 'shadow_burden' }],
  },
  veteran_victory_5: {
    id: 'veteran_victory_5',
    title: '루프 개척자',
    description: '누적 5회 승리를 달성했다.',
    icon: '🗝️',
    trigger: 'run_completed',
    category: 'run',
    scope: 'account',
    condition: { type: 'victories', count: 5 },
    rewards: [{ type: 'unlock', contentType: 'relic', contentId: 'dimension_key' }],
  },
  cursed_conqueror_3: {
    id: 'cursed_conqueror_3',
    title: '저주 정복자 III',
    description: '저주를 건 상태로 3회 승리했다.',
    icon: '🌘',
    trigger: 'run_completed',
    category: 'challenge',
    scope: 'account',
    condition: { type: 'cursed_victories', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'curse', contentId: 'ruinous_tide' }],
  },
  scarred_return_3: {
    id: 'scarred_return_3',
    title: '상처 입은 귀환',
    description: '패배 또는 중도 포기를 3회 겪었다.',
    icon: '🩹',
    trigger: 'run_completed',
    category: 'challenge',
    scope: 'account',
    condition: { type: 'failures', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'relic', contentId: 'eternal_fragment' }],
  },
  chain_master_12: {
    id: 'chain_master_12',
    title: '연쇄의 대가',
    description: '최고 연쇄 12를 달성했다.',
    icon: '🧠',
    trigger: 'run_completed',
    category: 'challenge',
    scope: 'account',
    condition: { type: 'best_chain', count: 12 },
    rewards: [{ type: 'unlock', contentType: 'relic', contentId: 'glitch_circuit' }],
  },
  merchant_ally: {
    id: 'merchant_ally',
    title: '상인의 인연',
    description: '길 잃은 상인을 구해냈다.',
    icon: '📿',
    trigger: 'run_completed',
    category: 'story',
    scope: 'account',
    condition: { type: 'world_memory_count', key: 'savedMerchant', count: 1 },
    rewards: [{ type: 'unlock', contentType: 'relic', contentId: 'ancient_battery' }],
  },
  story_seeker_5: {
    id: 'story_seeker_5',
    title: '기억 수집가',
    description: '스토리 조각 5개를 모았다.',
    icon: '🧵',
    trigger: 'run_completed',
    category: 'story',
    scope: 'account',
    condition: { type: 'story_pieces', count: 5 },
    rewards: [{ type: 'unlock', contentType: 'relic', contentId: 'memory_thread' }],
  },
  codex_survey_20: {
    id: 'codex_survey_20',
    title: '현장 조사원',
    description: '도감 항목 20개를 기록했다.',
    icon: '📓',
    trigger: 'run_completed',
    category: 'collection',
    scope: 'account',
    condition: { type: 'codex_entries', count: 20 },
    rewards: [{ type: 'unlock', contentType: 'relic', contentId: 'field_journal' }],
  },
  enemy_survey_12: {
    id: 'enemy_survey_12',
    title: '야전 생물학자',
    description: '적 도감 12종을 기록했다.',
    icon: '🏮',
    trigger: 'run_completed',
    category: 'collection',
    scope: 'account',
    condition: { type: 'codex_enemies', count: 12 },
    rewards: [{ type: 'unlock', contentType: 'relic', contentId: 'curator_lantern' }],
  },
  card_survey_15: {
    id: 'card_survey_15',
    title: '전투 서기관',
    description: '카드 도감 15장을 기록했다.',
    icon: '🖋',
    trigger: 'run_completed',
    category: 'collection',
    scope: 'account',
    condition: { type: 'codex_cards', count: 15 },
    rewards: [{ type: 'unlock', contentType: 'relic', contentId: 'ink_reservoir' }],
  },
  relic_survey_12: {
    id: 'relic_survey_12',
    title: '표본 수집가',
    description: '유물 도감 12종을 기록했다.',
    icon: '🧰',
    trigger: 'run_completed',
    category: 'collection',
    scope: 'account',
    condition: { type: 'codex_items', count: 12 },
    rewards: [{ type: 'unlock', contentType: 'relic', contentId: 'specimen_case' }],
  },
  swordsman_mastery_3: {
    id: 'swordsman_mastery_3',
    title: '잔향검사 숙련',
    description: '잔향검사 숙련도 3을 달성했다.',
    icon: '🗡',
    trigger: 'run_completed',
    category: 'class',
    scope: 'class',
    condition: { type: 'class_level', classId: 'swordsman', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'card', contentId: 'blade_dance', classId: 'swordsman' }],
  },
  mage_mastery_3: {
    id: 'mage_mastery_3',
    title: '공허술사 숙련',
    description: '공허술사 숙련도 3을 달성했다.',
    icon: '🔮',
    trigger: 'run_completed',
    category: 'class',
    scope: 'class',
    condition: { type: 'class_level', classId: 'mage', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'relic', contentId: 'void_compass', classId: 'mage' }],
  },
  hunter_mastery_3: {
    id: 'hunter_mastery_3',
    title: '사냥꾼 숙련',
    description: '사냥꾼 숙련도 3을 달성했다.',
    icon: '🏹',
    trigger: 'run_completed',
    category: 'class',
    scope: 'class',
    condition: { type: 'class_level', classId: 'hunter', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'card', contentId: 'combat_frenzy', classId: 'hunter' }],
  },
  paladin_mastery_3: {
    id: 'paladin_mastery_3',
    title: '성기사 숙련',
    description: '성기사 숙련도 3을 달성했다.',
    icon: '🛡',
    trigger: 'run_completed',
    category: 'class',
    scope: 'class',
    condition: { type: 'class_level', classId: 'paladin', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'card', contentId: 'judgement', classId: 'paladin' }],
  },
  berserker_mastery_3: {
    id: 'berserker_mastery_3',
    title: '광전사 숙련',
    description: '광전사 숙련도 3을 달성했다.',
    icon: '🪓',
    trigger: 'run_completed',
    category: 'class',
    scope: 'class',
    condition: { type: 'class_level', classId: 'berserker', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'card', contentId: 'frenzy_strike', classId: 'berserker' }],
  },
  guardian_mastery_3: {
    id: 'guardian_mastery_3',
    title: '수호자 숙련',
    description: '수호자 숙련도 3을 달성했다.',
    icon: '🗿',
    trigger: 'run_completed',
    category: 'class',
    scope: 'class',
    condition: { type: 'class_level', classId: 'guardian', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'relic', contentId: 'guardian_seal', classId: 'guardian' }],
  },
});
