export const ACHIEVEMENTS = Object.freeze({
  first_victory: {
    id: 'first_victory',
    trigger: 'run_completed',
    category: 'run',
    scope: 'account',
    condition: { type: 'victories', count: 1 },
    rewards: [{ type: 'unlock', contentType: 'curse', contentId: 'blood_moon' }],
  },
  cursed_conqueror_1: {
    id: 'cursed_conqueror_1',
    trigger: 'run_completed',
    category: 'challenge',
    scope: 'account',
    condition: { type: 'cursed_victories', count: 1 },
    rewards: [{ type: 'unlock', contentType: 'curse', contentId: 'void_oath' }],
  },
  veteran_victory_3: {
    id: 'veteran_victory_3',
    trigger: 'run_completed',
    category: 'run',
    scope: 'account',
    condition: { type: 'victories', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'curse', contentId: 'shadow_burden' }],
  },
  cursed_conqueror_3: {
    id: 'cursed_conqueror_3',
    trigger: 'run_completed',
    category: 'challenge',
    scope: 'account',
    condition: { type: 'cursed_victories', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'curse', contentId: 'ruinous_tide' }],
  },
  swordsman_mastery_3: {
    id: 'swordsman_mastery_3',
    trigger: 'run_completed',
    category: 'class',
    scope: 'class',
    condition: { type: 'class_level', classId: 'swordsman', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'card', contentId: 'blade_dance', classId: 'swordsman' }],
  },
  mage_mastery_3: {
    id: 'mage_mastery_3',
    trigger: 'run_completed',
    category: 'class',
    scope: 'class',
    condition: { type: 'class_level', classId: 'mage', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'relic', contentId: 'void_compass', classId: 'mage' }],
  },
  hunter_mastery_3: {
    id: 'hunter_mastery_3',
    trigger: 'run_completed',
    category: 'class',
    scope: 'class',
    condition: { type: 'class_level', classId: 'hunter', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'card', contentId: 'combat_frenzy', classId: 'hunter' }],
  },
  paladin_mastery_3: {
    id: 'paladin_mastery_3',
    trigger: 'run_completed',
    category: 'class',
    scope: 'class',
    condition: { type: 'class_level', classId: 'paladin', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'card', contentId: 'judgement', classId: 'paladin' }],
  },
  berserker_mastery_3: {
    id: 'berserker_mastery_3',
    trigger: 'run_completed',
    category: 'class',
    scope: 'class',
    condition: { type: 'class_level', classId: 'berserker', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'card', contentId: 'frenzy_strike', classId: 'berserker' }],
  },
  guardian_mastery_3: {
    id: 'guardian_mastery_3',
    trigger: 'run_completed',
    category: 'class',
    scope: 'class',
    condition: { type: 'class_level', classId: 'guardian', count: 3 },
    rewards: [{ type: 'unlock', contentType: 'relic', contentId: 'guardian_seal', classId: 'guardian' }],
  },
});
