export const UNLOCKABLES = Object.freeze({
  curses: {
    blood_moon: {
      id: 'blood_moon',
      scope: 'account',
      requires: ['first_victory'],
      unlockHint: '첫 승리 필요',
      visibleBeforeUnlock: true,
    },
    void_oath: {
      id: 'void_oath',
      scope: 'account',
      requires: ['cursed_conqueror_1'],
      unlockHint: '저주 활성화 상태로 승리 1회 필요',
      visibleBeforeUnlock: true,
    },
    shadow_burden: {
      id: 'shadow_burden',
      scope: 'account',
      requires: ['veteran_victory_3'],
      unlockHint: '승리 3회 필요',
      visibleBeforeUnlock: true,
    },
    ruinous_tide: {
      id: 'ruinous_tide',
      scope: 'account',
      requires: ['cursed_conqueror_3'],
      unlockHint: '저주 활성화 상태로 승리 3회 필요',
      visibleBeforeUnlock: true,
    },
  },
  relics: {
    void_compass: {
      id: 'void_compass',
      scope: 'class',
      classId: 'mage',
      requires: ['mage_mastery_3'],
      unlockHint: '메아리술사 숙련도 3 달성 필요',
      displayName: '공허의 나침반',
      visibleBeforeUnlock: false,
    },
    guardian_seal: {
      id: 'guardian_seal',
      scope: 'class',
      classId: 'guardian',
      requires: ['guardian_mastery_3'],
      unlockHint: '무음수호자 숙련도 3 달성 필요',
      displayName: '수호자의 인장',
      visibleBeforeUnlock: false,
    },
  },
  cards: {
    blade_dance: {
      id: 'blade_dance',
      scope: 'class',
      classId: 'swordsman',
      requires: ['swordsman_mastery_3'],
      unlockHint: '잔향검사 숙련도 3 달성 필요',
      displayName: '검무',
      visibleBeforeUnlock: false,
    },
    combat_frenzy: {
      id: 'combat_frenzy',
      scope: 'class',
      classId: 'hunter',
      requires: ['hunter_mastery_3'],
      unlockHint: '침묵사냥꾼 숙련도 3 달성 필요',
      displayName: '전투 광란',
      visibleBeforeUnlock: false,
    },
    judgement: {
      id: 'judgement',
      scope: 'class',
      classId: 'paladin',
      requires: ['paladin_mastery_3'],
      unlockHint: '찬송기사 숙련도 3 달성 필요',
      displayName: '심판',
      visibleBeforeUnlock: false,
    },
    frenzy_strike: {
      id: 'frenzy_strike',
      scope: 'class',
      classId: 'berserker',
      requires: ['berserker_mastery_3'],
      unlockHint: '파음전사 숙련도 3 달성 필요',
      displayName: '광분 타격',
      visibleBeforeUnlock: false,
    },
  },
});
