export const UNLOCKABLES = Object.freeze({
  curses: {
    blood_moon: {
      id: 'blood_moon',
      scope: 'account',
      requires: ['first_victory'],
      unlockHint: '첫 승리 필요',
      displayName: '핏빛 월식',
      visibleBeforeUnlock: true,
    },
    void_oath: {
      id: 'void_oath',
      scope: 'account',
      requires: ['cursed_conqueror_1'],
      unlockHint: '저주 활성화 상태로 승리 1회 필요',
      displayName: '공허의 맹세',
      visibleBeforeUnlock: true,
    },
    shadow_burden: {
      id: 'shadow_burden',
      scope: 'account',
      requires: ['veteran_victory_3'],
      unlockHint: '승리 3회 필요',
      displayName: '그림자 짐',
      visibleBeforeUnlock: true,
    },
    ruinous_tide: {
      id: 'ruinous_tide',
      scope: 'account',
      requires: ['cursed_conqueror_3'],
      unlockHint: '저주 활성화 상태로 승리 3회 필요',
      displayName: '파멸의 조류',
      visibleBeforeUnlock: true,
    },
  },
  relics: {
    dimension_key: {
      id: 'dimension_key',
      scope: 'account',
      requires: ['veteran_victory_5'],
      unlockHint: '승리 5회 필요',
      displayName: '차원 열쇠',
      visibleBeforeUnlock: false,
    },
    eternal_fragment: {
      id: 'eternal_fragment',
      scope: 'account',
      requires: ['scarred_return_3'],
      unlockHint: '패배 또는 중도 포기 3회 필요',
      displayName: '영원의 파편',
      visibleBeforeUnlock: false,
    },
    glitch_circuit: {
      id: 'glitch_circuit',
      scope: 'account',
      requires: ['chain_master_12'],
      unlockHint: '최고 연쇄 12 필요',
      displayName: '글리치 회로',
      visibleBeforeUnlock: false,
    },
    ancient_battery: {
      id: 'ancient_battery',
      scope: 'account',
      requires: ['merchant_ally'],
      unlockHint: '잃어버린 상인을 1회 구출 필요',
      displayName: '고대 배터리',
      visibleBeforeUnlock: false,
    },
    memory_thread: {
      id: 'memory_thread',
      scope: 'account',
      requires: ['story_seeker_5'],
      unlockHint: '스토리 조각 5개 필요',
      displayName: '기억의 실타래',
      visibleBeforeUnlock: false,
    },
    field_journal: {
      id: 'field_journal',
      scope: 'account',
      requires: ['codex_survey_20'],
      unlockHint: '도감 기록 20개 필요',
      displayName: '현장 기록장',
      visibleBeforeUnlock: false,
    },
    curator_lantern: {
      id: 'curator_lantern',
      scope: 'account',
      requires: ['enemy_survey_12'],
      unlockHint: '적 도감 12종 필요',
      displayName: '큐레이터의 등불',
      visibleBeforeUnlock: false,
    },
    ink_reservoir: {
      id: 'ink_reservoir',
      scope: 'account',
      requires: ['card_survey_15'],
      unlockHint: '카드 도감 15장 필요',
      displayName: '잉크 저장고',
      visibleBeforeUnlock: false,
    },
    specimen_case: {
      id: 'specimen_case',
      scope: 'account',
      requires: ['relic_survey_12'],
      unlockHint: '유물 도감 12종 필요',
      displayName: '표본 보관함',
      visibleBeforeUnlock: false,
    },
    void_compass: {
      id: 'void_compass',
      scope: 'class',
      classId: 'mage',
      requires: ['mage_mastery_3'],
      unlockHint: '메아리술사 숙련도 3 달성 필요',
      displayName: '공허의 나침반',
      visibleBeforeUnlock: false,
    },
    guardian_seal: {
      id: 'guardian_seal',
      scope: 'class',
      classId: 'guardian',
      requires: ['guardian_mastery_3'],
      unlockHint: '무음수호자 숙련도 3 달성 필요',
      displayName: '수호자의 인장',
      visibleBeforeUnlock: false,
    },
  },
  cards: {
    blade_dance: {
      id: 'blade_dance',
      scope: 'class',
      classId: 'swordsman',
      requires: ['swordsman_mastery_3'],
      unlockHint: '잔향검사 숙련도 3 달성 필요',
      displayName: '검무',
      visibleBeforeUnlock: false,
    },
    combat_frenzy: {
      id: 'combat_frenzy',
      scope: 'class',
      classId: 'hunter',
      requires: ['hunter_mastery_3'],
      unlockHint: '침묵사냥꾼 숙련도 3 달성 필요',
      displayName: '전투 광란',
      visibleBeforeUnlock: false,
    },
    judgement: {
      id: 'judgement',
      scope: 'class',
      classId: 'paladin',
      requires: ['paladin_mastery_3'],
      unlockHint: '찬송기사 숙련도 3 달성 필요',
      displayName: '심판',
      visibleBeforeUnlock: false,
    },
    frenzy_strike: {
      id: 'frenzy_strike',
      scope: 'class',
      classId: 'berserker',
      requires: ['berserker_mastery_3'],
      unlockHint: '파음전사 숙련도 3 달성 필요',
      displayName: '광분 타격',
      visibleBeforeUnlock: false,
    },
  },
});
