export const LEGACY_WINDOW_COMMAND_NAMES = [
  'shiftAscension', 'toggleEndlessMode', 'cycleRunCurse', 'selectRunCurse',
  'openCodexFromTitle', 'showCharacterSelect', 'continueRun', 'backToTitle', 'openRunSettings',
  'closeRunSettings', 'startGame', 'selectClass', 'showDmgPopup', 'showCombatSummary',
  'showItemTooltip', 'hideItemTooltip', 'showWorldMemoryNotice', 'quitGame',
  'showFullMap', 'toggleHudPin', 'showIntentTooltip', 'hideIntentTooltip',
  'renderCombatEnemies', 'updateEnemyHpUI', 'renderCombatCards', 'renderHand',
  'updateEchoSkillBtn', 'updateCombatLog', 'updateHandFanEffect',
  'closeDeckView', 'closeCodex', 'updateNoiseWidget', 'updateClassSpecialUI',
  'selectTarget', 'showRewardScreen', 'takeRewardItem', 'takeRewardUpgrade',
  'takeRewardRemove', 'setMasterVolume', 'setSfxVolume', 'setAmbientVolume',
  'endPlayerTurn', 'takeRewardCard', 'moveToNode', 'toggleHelp', 'togglePause',
  'abandonRun', 'confirmAbandon', 'showDeckView', 'useEchoSkill', 'drawCard',
  'resolveEvent', 'returnToGame', 'openCodex', 'toggleCombatInfo', 'updateStatusDisplay',
  'showCardPlayEffect',
  'openSettings', 'closeSettings', 'setSettingsTab', 'resetSettings',
  'applySettingVolume', 'applySettingVisual', 'applySettingAccessibility',
  'startSettingsRebind', 'toggleSettingMute',
];
